"""
Django settings for refreshin project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'sa!#1s$w&@vjw_$4(28ao+mhnnlf#_d%_%)udc6$pt$cfsv+nn'
TWITTER_CONSUMER_KEY = 'DnipuKABqH2FuiqaCwZLIh0YN'
TWITTER_CONSUMER_SECRET = 'Y5sP66Jt9JpbPALsdpOPGGxSByyKaVD8FxghBY4bogF0nBBczR'
TWITTER_CONSUMER_ACCESS_TOKEN_KEY = '2705228442-ppFuMoF6UYv79x7kbXWkwJD4AFJQlvt4JH6BA66'
TWITTER_CONSUMER_TOKEN_SECRET = 'aFpqd03i5LFR4Qt5HhVfyYkmyDzauq4CdMXdcgp9Rk3Me'
# api = twitter.Api(consumer_key='DnipuKABqH2FuiqaCwZLIh0YN',
#                       consumer_secret='Y5sP66Jt9JpbPALsdpOPGGxSByyKaVD8FxghBY4bogF0nBBczR',
#                       access_token_key='2705228442-ppFuMoF6UYv79x7kbXWkwJD4AFJQlvt4JH6BA66',
#                       access_token_secret='aFpqd03i5LFR4Qt5HhVfyYkmyDzauq4CdMXdcgp9Rk3Me')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'polls.apps.PollsConfig',
    # 'detection.apps.DetectionConfig',
    'stats.apps.StatsConfig',
    'bootstrap4form'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'refreshin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'polls/../polls/templates'),
                 os.path.join(BASE_DIR, 'detection/../detection/templates'),
                 os.path.join(BASE_DIR, 'stats/../stats/templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'refreshin.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'MyDatabase'),
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sccxqbkl',
        'USER': 'sccxqbkl',
        'PASSWORD': 'bK-UULEqBTN6DFlgaLpBUNPu8sX6ZP-J',
        'HOST': 'raja.db.elephantsql.com',
        'PORT': '5432'
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
